export { default as HeaderImage} from "./Greenacy.org-Favicon.png";
export { default as FooterBg } from "./footer.jpg";
export { default as GreenacyWhiteLogo } from "./Greenacy-White-Logo.png";
export { default as Interior_Design_Firm } from "./3_Interior_Design_Firm-Img_1.jpg";
export { default as Interior_Design_Firm1 } from "./3_Interior_Design_Firm-Img_2.jpg";
export { default as Photo7} from "./photo-7-1536x1024.jpg";     
export { default as Photo4} from "./photo-3-1536x1024.jpg"; 
export { default as Photo3} from "./photo-2-1-1536x1024.jpg"; 
export { default as Icon6} from "./icon-6.jpg"; 
export { default as Icon7} from "./icon-7.jpg";  
export { default as Icon8} from "./icon-8.jpg";  
export { default as Icon9} from "./icon-9.jpg";  
export { default as Icon10} from "./icon-10.jpg";  
export { default as Icon11} from "./icon-11.jpg"; 
export { default as Iconblog} from "./Greenacy-globe.png"; 
export { default as Backgroud} from "./background-3.jpg"; 
export { default as Eve} from "./eve.webp"; 
export { default as Eve1} from "./DALLE22.webp"; 
export { default as Eve2} from "./DALL·E-2025-03-22-14.36.30-A-conceptual-image-for-a-Water-Watch-Campaign-by-a-climate-action-non-profit.-The-scene-should-emphasize-water-conservation-and-clean-water-initiati-1-768x439.webp"; 
export { default as Eve3} from "./DALLE45.webp"; 
export { default as Eve4} from "./DALL·E-2025-03-22-14.43.31-A-conceptual-image-for-a-Green-Tech-Innovation-event-by-a-climate-action-non-profit.-The-scene-should-highlight-futuristic-and-eco-friendly-technolo-1-768x439.webp"; 
export { default as Eve5} from "./DALL·E-2025-03-22-14.54.46-A-conceptual-image-for-Love-Local-Live-Green-—-an-eco-business-event-by-a-climate-action-non-profit.-The-scene-should-showcase-a-vibrant-local-mark-1-768x439.webp"; 
export { default as Eve6} from "./DALL·E-2025-03-22-14.54.46-A-conceptual-image-for-Love-Local-Live-Green-—-an-eco-business-event-by-a-climate-action-non-profit.-The-scene-should-showcase-a-vibrant-local-mark-1-768x439.webp"; 
export { default as Eve7} from "./DALL·E-2025-03-22-15.00.34-A-conceptual-image-for-a-Sustainable-Living-Bootcamp-organized-by-a-climate-action-non-profit.-The-scene-should-resemble-an-immersive-eco-training-e-.webp"; 
export { default as Eve8} from "./DALL·E-2025-03-22-15.01.33-A-conceptual-image-for-a-Climate-Advocacy-Policy-event-by-a-climate-action-non-profit.-The-scene-should-visually-represent-the-intersection-of-env-1-.webp"; 
export { default as Eve9} from "./DALL·E-2025-03-22-14.56.32-A-conceptual-image-for-a-Plastic-Free-Campus-initiative-by-a-climate-action-non-profit.-The-scene-should-depict-a-clean-and-green-school-or-universi-.webp"; 
export { default as Eve10} from "./DALL·E-2025-03-22-14.40.13-A-conceptual-image-for-a-Clean-Campus-Drive-organized-by-a-climate-action-non-profit.-The-scene-should-show-a-neat-and-green-school-or-college-campu-1-768x439.webp"; 
export {default as Person1} from "./photo-6-2-768x512.jpg";
export {default as Person2} from "./photo-2-1-1536x1024.jpg"  ;
export {default as Person3} from "./photo-3-1536x1024.jpg";
export {default as Person5} from "./photo-7-1536x1024.jpg";
export {default as Person4} from "./photo-1-1.jpg";
export {default as Background1} from "./background.jpg";
export {default as Closed} from "./GreenacyClosed.png";
export {default as Blog1 } from "./Greenacy-2937-768x512.jpeg";
export {default as Blog2} from "./Greenacy-3403.jpg";
export {default as Blog3} from "./Greenacy-3836.webp";
export {default as Blog4} from "./Greenacy-Blog-2828-768x432.jpg";
export {default as Blog5} from "./Greenacy-Blog-Post-4534-768x512.webp";
export {default as Blog6} from "./Greenacy-5322-768x517.webp";
export {default as HeroBg} from "./photo-1-1.jpg";
export {default as Logo1} from "./logo-1.png";
export {default as Logo2} from "./logo-2.png";
export {default as Logo3} from "./logo-3.png";
export {default as Logo4} from "./logo-4.png";
export {default as Logo5} from "./logo-5.png";
export {default as Team1} from "./Greenacy-Team-460.png";
export {default as Team2} from "./Greenacy-Team-707.png";
export {default as Team3} from "./Greenacy-Team-975.png";
export {default as Vision1} from "./team-of-young-successful-designers-gathered-by-wor-2023-11-27-04-57-08-utc_result-768x512.webp";
export {default as Vision2} from "./photo-5-768x512.jpg";
export {default as Vision3} from "./Greenacy-3283-768x480.jpg";


